apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "group-manager.prefix" . }}-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "group-manager.prefix" . }}-proxy
  template:
    metadata:
      labels:
        app: {{ include "group-manager.prefix" . }}-proxy
    spec:
      containers:
      - name: {{ include "group-manager.prefix" . }}-proxy
        # TODO: tag
        image: moreillon/api-proxy
        ports:
        - containerPort: 80
        env:
        - name: PROXY_ROOT
          value: http://{{ include "group-manager.prefix" . }}-gui
        - name: PROXY_API
          value: http://{{ include "group-manager.prefix" . }}-api
        - name: PROXY_AUTH
          value: {{ .Values.auth.apiUrl }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "group-manager.prefix" . }}-proxy
spec:
  type: NodePort
  selector:
    app: {{ include "group-manager.prefix" . }}-proxy
  ports:
  - port: 80
    nodePort: {{ .Values.nodePorts.gui }}
