name: user-manager

jwt_secret: keyboardcat

# TODO: allow to use existing mongoDB
# api:

mongo:
  enabled: true
  pvc: 100Gi

nodePorts:
  api: 30070
  gui: 30080

ingress:
  enabled: true
  host: null
  subdomain: subdo

global:
  ingress:
    host: banana.test.home.maximemoreillon.com
