# Default values for user-manager-neo4j.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


neo4j:
  username: neo4j
  password: neo4Jpassword
  pvcSize: 100Gi

admin:
  username: admin
  password: admin

nodePorts:
  api: 30016
  gui: 30017

jwt_secret: keyboardcat
