nameOverride: face-recognition

persistence:
  size: 100Gi

service:
  type: NodePort
  nodePort: 30080

mongodb:
  enabled: true
  persistence:
    size: 100Gi
  auth:
    enabled: false

auth:
  enabled: false
  mongodb:
    enabled: false
    # Dummy password to facilitate upgrades
    rootPassword: banana
