apiVersion: v2
name: shcp
description: A Helm chart for deploy SHCP
type: application
version: 0.1.0
appVersion: "1.16.0"
icon: https://raw.githubusercontent.com/maximemoreillon/helm-repository/master/charts/shcp/icon.png
