apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "camera-viewer.fullname" .}}-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{include "camera-viewer.fullname" .}}-back
  template:
    metadata:
      labels:
        app: {{include "camera-viewer.fullname" .}}-back
    spec:
      containers:
        - name: {{include "camera-viewer.fullname" .}}-back
          image: moreillon/camera-proxy
          env:
            - name: MONGODB_HOST
              value: {{.Release.Name}}-mongodb
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: {{include "camera-viewer.fullname" .}}-back
spec:
  type: ClusterIP
  selector:
    app: {{include "camera-viewer.fullname" .}}-back
  ports:
    - port: 80

