apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}-back
  template:
    metadata:
      labels:
        app: {{.Values.name}}-back
    spec:
      containers:
        - name: {{.Values.name}}-back
          image: moreillon/camera-proxy
          env:
            # MongoDB
            - name: MONGODB_URL
              value: mongodb://{{.Values.name}}-mongo
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-back
spec:
  type: ClusterIP
  selector:
    app: {{.Values.name}}-back
  ports:
    - port: 80

