apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "camera-viewer.fullname" .}}-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{include "camera-viewer.fullname" .}}-front
  template:
    metadata:
      labels:
        app: {{include "camera-viewer.fullname" .}}-front
    spec:
      containers:
        - name: {{include "camera-viewer.fullname" .}}-front
          image: moreillon/camera-viewer
          env:
            - name: VUE_APP_API_URL
              value: /proxy/api
            # TODO: optional auth
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: {{include "camera-viewer.fullname" .}}-front
spec:
  type: ClusterIP
  selector:
    app: {{include "camera-viewer.fullname" .}}-front
  ports:
    - port: 80
