apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}-proxy
  template:
    metadata:
      labels:
        app: {{.Values.name}}-proxy
    spec:
      containers:
        - name: {{.Values.name}}-proxy
          image: moreillon/api-proxy:e80c1d87
          env:
            - name: PROXY_API
              value: http://{{.Values.name}}-back
            - name: PROXY_ROOT
              value: http://{{.Values.name}}-front
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-proxy
spec:
  type: NodePort
  selector:
    app: {{.Values.name}}-proxy
  ports:
    - port: 80
      nodePort: {{.Values.nodePort}}
