apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "camera-viewer.fullname" .}}-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{include "camera-viewer.fullname" .}}-proxy
  template:
    metadata:
      labels:
        app: {{include "camera-viewer.fullname" .}}-proxy
    spec:
      containers:
        - name: {{include "camera-viewer.fullname" .}}-proxy
          image: moreillon/api-proxy:e80c1d87
          env:
            - name: PROXY_API
              value: http://{{include "camera-viewer.fullname" .}}-back
            - name: PROXY_ROOT
              value: http://{{include "camera-viewer.fullname" .}}-front
            - name: PROXY_AUTH
              value: http://{{.Release.Name}}-auth
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{include "camera-viewer.fullname" .}}-proxy
spec:
  type: NodePort
  selector:
    app: {{include "camera-viewer.fullname" .}}-proxy
  ports:
    - port: 80
      nodePort: {{.Values.nodePort}}
