apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-proxy
  template:
    metadata:
      labels:
        app: api-proxy
    spec:
      containers:
        - name: api-proxy
          image: moreillon/api-proxy
          ports:
            - containerPort: 80
          env:
            - name: PROXY_API
              value: http://{{.Values.name}}-api
            - name: PROXY_ROOT
              value: http://{{.Values.name}}-gui
