{{ $ingressEnabled := eq (include "food-manager.ingress.enabled" .) "true"}}
{{- if $ingressEnabled -}}
{{ $resourceName := "gui" }}
{{ $fullName := printf "%s-%s" (include "food-manager.fullName" .) $resourceName | trunc 63 | trimSuffix "-" }}
{{ $host := include "food-manager.ingress.host" .}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations: {{ include "food-manager.ingress.annotations" .}}
spec:
  tls:
    - hosts:
        - {{ $host }}
      secretName: {{ $fullName }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: {{ $fullName }}
                port:
                  number: 80
{{- end }}
