{{ $resourceName := "gui" }}
{{ $fullName := printf "%s-%s" (include "food-manager.fullName" .) $resourceName | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
spec:
  selector:
    app: {{ $fullName }}
  type: ClusterIP
  ports:
  - port: 80
    