{{ $resourceName := "proxy" }}
{{ $fullName := printf "%s-%s" (include "user-manager.fullName" .) $resourceName | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      containers:
      - name: {{ $fullName }}
        image: moreillon/api-proxy
        ports:
        - containerPort: 80
        env:
        # FIXME: Might not match if truncated
        - name: PROXY_API
          value: http://{{ include "user-manager.fullName" . }}-api
        - name: PROXY_ROOT
          value: http://{{ include "user-manager.fullName" . }}-gui
