{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "user-manager.fullname" . }}-proxy
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ include "user-manager.ingress.host" . }}
      secretName: {{ include "user-manager.fullname" . }}-proxy
  rules:
    - host: {{ include "user-manager.ingress.host" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: {{ include "user-manager.fullname" . }}-proxy
                port:
                  number: 80
{{- end }}
