apiVersion: v1
kind: Service
metadata:
  name: {{include "face-recognition.fullname" .}}
spec:
  type: ClusterIP
  selector:
    app: {{include "face-recognition.fullname" .}}
  ports:
    - port: 80
