apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-api
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-api
    spec:
      containers:
      - name: {{ .Values.name }}-api
        # TODO: tag
        image: moreillon/user-manager-mongoose
        ports:
        - containerPort: 80
        env:
        - name: MONGODB_URL
          value: mongodb://{{ .Values.name }}-mongo
        - name: JWT_SECRET
          value: {{ .Values.jwt_secret }}
