{{ $resourceName := "api" }}
{{ $fullName := printf "%s-%s" (include "user-manager.fullName" .) $resourceName | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
spec:
  selector:
    app: {{ $fullName }}
{{- if (.Values.nodePorts).api }}
  type: NodePort
  ports:
  - port: 80
    nodePort: {{ .Values.nodePorts.api }}
{{- else }}
  type: ClusterIP
  ports:
  - port: 80
{{- end }}
