{{ $resourceName := "gui" }}
{{ $fullname := printf "%s-%s" (include "user-manager.fullname" .) $resourceName | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullname }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ $fullname }}
        image: {{ .Values.gui.image }}
        ports:
        - containerPort: 80
        env:
        - name: VUE_APP_USER_MANAGER_API_URL
          value: /api
