{{ $resourceName := "gui" }}
{{ $fullname := printf "%s-%s" (include "user-manager.fullname" .) $resourceName | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
spec:
  type: ClusterIP
  selector:
    app: {{ $fullname }}
  ports:
  - port: 80
