apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
      - name: {{ .Release.Name }}-api
        image: moreillon/user-manager
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
           name: {{.Release.Name}}-credentials
        env:
        - name: NEO4J_URL
          value: bolt://{{.Release.Name}}-neo4j:7687
