apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-api
  ports:
  - port: 80
    nodePort: {{ .Values.nodePorts.api }}
