apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "200Gi" .Values.pvcSizes.db}}
