{{- if .Values.mongo.enabled -}}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "200Gi" .Values.mongo.pvc}}

{{- end }}
