{{- if .Values.mongo.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-mongo
spec:
  ports:
  - port: 27017
  selector:
    app: {{ .Values.name }}-mongo
  type: ClusterIP
  
{{- end }}
