apiVersion: v2
name: food-manager
description: A Helm chart to deploy Food-manager, a calorie and macro tracking application

type: application

version: 0.2.10

appVersion: "1.16.0"

icon: https://raw.githubusercontent.com/maximemoreillon/helm-repository/master/charts/food-manager/icon.png

dependencies:
  - name: user-manager-mongodb
    version: 0.3.5
    repository: https://maximemoreillon.github.io/helm-repository
    condition: auth.enabled
    alias: auth

  - name: mongodb
    version: 13.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
