# Default values for food-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global values shared with subcharts
global:
  ingress:
    host: food.test.home.maximemoreillon.com

  mongodb:
    url: mongodb://192.168.1.2:30717

nodePort: 30400

mongodb:
  enabled: false

# TODO: consider global
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

user-manager-mongoose:
  nameOverride: user-manager
  enabled: true

  # Disable subchart mongodb because using that of parent
  # TODO: would be simpler as global
  mongodb:
    enabled: false

  ingress:
    # TODO: should match that of parent
    enabled: false
    subdomain: users
    # Default annotations are fine
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   cert-manager.io/cluster-issuer: letsencrypt-prod
