global:
  ingress:
    enabled: false
    host: food.test.home.maximemoreillon.com
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod

service:
  type: NodePort
  nodePort: 30400

mongodb:
  enabled: true
  persistence:
    size: 100Gi
  auth:
    enabled: false

auth:
  enabled: true
  mongodb:
    enabled: false
  ingress:
    subdomain: auth
  nodePorts:
    gui: 30401
