image:
  repository: moreillon/food-manager
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: NodePort
  nodePort: 31081

env: []
envFrom: []

mongodb:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/mongodb
  persistence:
    size: 100Gi
  auth:
    enabled: false
