mongodb:
  enabled: true
  persistence:
    size: 100Gi
  auth:
    enabled: false

auth:
  enabled: false
  mongodb:
    enabled: false
  ingress:
    subdomain: auth
  nodePorts:
    gui: 30401
    
# API Gateway
kong:
  enabled: true
  admin:
    enabled: false # Do not create a service for the admin API
  manager:
    enabled: false # Do not create a service for Kong Manager
  ingressController:
    enabled: false
  env:
    database: "off"
    dns_order: A,CNAME,LAST,SRV
  dblessConfig:
    configMap: kong-config
  proxy:
    type: NodePort
    http:
      nodePort: 31081
    tls:
      enabled: false
