mongodb:
  enabled: true
  persistence:
    size: 100Gi
  auth:
    enabled: false

auth:
  enabled: false
  mongodb:
    enabled: false
  ingress:
    subdomain: auth
  nodePorts:
    gui: 30401

kong:
  enabled: true
  admin:
    enabled: false
  env:
    database: "off"
    dns_order: A,CNAME,LAST,SRV
  dblessConfig:
    configMap: kong-config
  ingressController:
    enabled: false
  proxy:
    type: NodePort
    http:
      nodePort: 31081
