# Default values for food-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global values shared with subcharts
global:
  enabled: false
  ingress:
    host: food.test.home.maximemoreillon.com
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod

nodePort: 30400

# Bitnami MongoDB chart
mongodb:
  enabled: true

# User-manager-mongoose chart
auth:
  enabled: false

  mongodb:
    enabled: false

  ingress:
    subdomain: auth
