# Default values for food-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global needed for subcharts
global:
  ingress:
    host: food.test.home.maximemoreillon.com

  # Using integrated MongoDB by setting url to null
  mongodb:
    url: mongodb://192.168.1.2:30717

nodePort: 30400

# TODO: consider global
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

user-manager-mongoose:
  prefix: users
  enabled: true

  # Disable subchart mongodb because using that of parent
  # TODO: would be simpler as global
  mongodb:
    enabled: true

  ingress:
    enabled: true
    subdomain: users
    # Default annotations are fine
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   cert-manager.io/cluster-issuer: letsencrypt-prod
