# Default values for food-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global values shared with subcharts
global:
  ingress:
    enabled: true
    host: food.test.home.maximemoreillon.com
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod

nodePort: 30400

# Bitnami MongoDB chart
mongodb:
  enabled: true
  persistence:
    size: 100Gi
  auth:
    enabled: false

# User-manager-mongoose chart
# Because alias does not work
auth:
  enabled: true
  mongodb:
    enabled: false
  ingress:
    subdomain: auth
