jwt_secret: keyboardcat

nodePorts:
  api: 30070
  # gui: 30080

ingress:
  enabled: false
  host: auth.example.com
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

# Bitnami MongoDB subchart
# https://artifacthub.io/packages/helm/bitnami/mongodb#mongodb-parameters
mongodb:
  enabled: true
  persistence:
    size: 100Gi
  auth:
    enabled: false
