{{ $fullName := include "food-manager.fullName" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      containers:
        - name: {{ $fullName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: NUXT_MONGOOSE_URI
              value: {{ include "food-manager.mongodb.url" . }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ $fullName }}
  ports:
    - port: 80
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
