apiVersion: v1
kind: Service
metadata:
  name: {{ include "food-manager.fullname" . }}
  labels:
    {{- include "food-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "food-manager.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
