{{- if .Values.mongodb.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "user-manager.prefix" . }}-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "200Gi" .Values.mongodb.pvc}}

{{- end }}
