apiVersion: v2
name: user-manager-neo4j
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.2.4

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.16.0

icon: https://raw.githubusercontent.com/maximemoreillon/helm-repository/master/charts/user-manager-neo4j/icon.png

dependencies:
  - name: neo4j
    version: 0.1.0
    repository: https://maximemoreillon.github.io/helm-repository
    condition: neo4j.enabled

  - name: group-manager
    version: 0.1.7
    repository: https://maximemoreillon.github.io/helm-repository
    condition: groups.enabled
    alias: groups
