nameOverride: user-manager

neo4j:
  enabled: true
  nameOverride: db
  neo4j:
    password: keyboardcat
    acceptLicenseAgreement: "yes"
  volumes:
    data:
      mode: defaultStorageClass

groups:
  enabled: false
  auth:
    name: user-manager-neo4j
  neo4j:
    username: neo4j
    password: keyboardcat

auth:
  jwt_secret: keyboardcat
  admin:
    username: admin
    password: admin

service:
  type: NodePort
  nodePort: 30080

api:
  image: moreillon/user-manager:v4.5.3

gui:
  image: moreillon/user-manager-front:v3.0.5

ingress:
  enabled: false
  # host: users.example.com
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   cert-manager.io/cluster-issuer: letsencrypt-prod
