nameOverride: user-manager

neo4j:
  enabled: true
  username: neo4j
  password: keyboardcat
  persistence:
    size: 100Gi

groups:
  enabled: false
  auth:
    name: user-manager-neo4j
  neo4j:
    username: neo4j
    password: keyboardcat

auth:
  jwt_secret: keyboardcat
  admin:
    username: admin
    password: admin

service:
  type: NodePort
  nodePort: 30080

ingress:
  enabled: false
  # host: users.example.com
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   cert-manager.io/cluster-issuer: letsencrypt-prod
