# Default values for user-manager-neo4j.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

neo4j:
  enabled: true
  username: neo4j
  password: keyboardcat
  persistence:
    size: 100Gi

admin:
  username: admin
  password: admin

nodePorts:
  api: 30016
  gui: 30017

jwt_secret: keyboardcat

ingress:
  # enabled: false
  # host: users.example.com
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   cert-manager.io/cluster-issuer: letsencrypt-prod
