apiVersion: v1
kind: Service
metadata:
  name: {{ include "resources.prefix" . }}-auth-gateway
spec:
  ports:
    - port: 80
      nodePort: 30022
  selector:
    app: {{ include "resources.prefix" . }}-auth-gateway
  type: NodePort
