apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto-user-manager.prefix" . }}-auth-gateway
spec:
  ports:
    - port: 80
  selector:
    app: {{ include "mosquitto-user-manager.prefix" . }}-auth-gateway
  type: ClusterIP
