apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto
  template:
    metadata:
      labels:
        app: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto
    spec:
      containers:
        - name: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto
          image: iegomez/mosquitto-go-auth
          ports:
            - containerPort: 1883 # MQTT
            - containerPort: 8883 # MQTTS
            - containerPort: 9001 # WSS
          volumeMounts:
            - mountPath: /etc/mosquitto/
              name: config
            - mountPath: /mosquitto/certs/
              name: certs
            - mountPath: /mosquitto/data/
              name: data
      volumes:
        - name: config
          configMap:
            name: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto-config
        - name: certs
          secret:
            secretName: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto-certs
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto-data
