
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.global.ingress.host }}
    secretName: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto-certs
  rules:
  - host: {{ .Values.global.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto-wss
            port: 
              number: 9001
{{- end }}
