apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto-mqtts
spec:
  type: NodePort
  selector:
    app: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto
  ports:
    - port: 8883
      name: mqtts
      nodePort: {{.Values.mosquitto.nodePorts.mqtts}}
    - port: 1883
      name: mqtt
      nodePort: {{.Values.mosquitto.nodePorts.mqtt}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto-wss
spec:
  type: ClusterIP
  selector:
    app: {{ include "mosquitto-user-manager.prefix" . }}-mosquitto
  ports:
    - port: 9001
