apiVersion: v2
name: group-manager
description: A Helm chart for Kubernetes

type: application

version: 0.1.8

appVersion: "1.16.0"

icon: https://raw.githubusercontent.com/maximemoreillon/helm-repository/master/charts/group-manager/icon.png
