apiVersion: v2
name: group-manager
description: A Helm chart to deploy Group-manager, a microservice to manage user groups

type: application

version: 0.1.9

appVersion: "1.16.0"

icon: https://raw.githubusercontent.com/maximemoreillon/helm-repository/master/charts/group-manager/icon.png
