# Default values for group-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: group-manager

image: moreillon/group-manager:v4.9.0

env: []
envFrom: []

service:
  type: ClusterIP
  nodePort: ""

neo4j:
  url: bolt://um-neo4j
  username: neo4j
  password: keyboardcat

auth:
  apiUrl: http://um-user-manager-test

gui:
  image: moreillon/group-manager-front:v3.3.1
  apiUrl: /api
  auth:
    loginurl: /auth/auth/login
    identificationUrl: /auth/users/self
  env: []

# API Gateway
kong:
  enabled: true
  admin:
    enabled: false # Do not create a service for the admin API
  manager:
    enabled: false # Do not create a service for Kong Manager
  ingressController:
    enabled: false
  env:
    database: "off"
    dns_order: A,CNAME,LAST,SRV
  dblessConfig:
    configMap: group-manager-kong-config
  proxy:
    type: NodePort
    http:
      nodePort: 31082
    tls:
      enabled: false
