# Default values for group-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: group-manager

nodePorts:
  api: 30018
  gui: 30019

# Overwriting default values of user-manager
user-manager-neo4j:
  name: gm-user-manager
