{{ $resourceName := "api" }}
{{ $fullName := printf "%s-%s" (include "food-manager.fullName" .) $resourceName | trunc 63 | trimSuffix "-" }}
# TODO: use a helper
{{ $mongodbUrl := printf "mongodb://%s-mongodb" .Release.Name }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$fullName}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # TODO: customizable
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$fullName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{$fullName}}
  template:
    metadata:
      labels:
        app: {{$fullName}}
    spec:
      containers:
        - name: {{$fullName}}
          image: moreillon/food-manager
          env:
            # DB
            - name: MONGODB_URL
              value: {{ $mongodbUrl }}
            {{- if .Values.auth.enabled }}
            # Warning: Hardcoded
            {{ $identificationUrl := printf "http://%s-user-manager-mongoose-api/users/self" .Release.Name }}
            - name: IDENTIFICATION_URL
              value: {{ $identificationUrl }}
            {{- end }}
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/src/app/uploads
              name: {{$fullName}}
      volumes:
        - name: {{$fullName}}
          persistentVolumeClaim:
            claimName: {{$fullName}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$fullName}}
spec:
  type: NodePort
  selector:
    app: {{$fullName}}
  ports:
    - port: 80
      nodePort: 30022
