{{ $fullName := include "food-manager.fullName" . | trunc 63 | trimSuffix "-" }}
{{ $mongodbUrl := include "food-manager.mongodb.url" . }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$fullName}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # TODO: customizable
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$fullName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{$fullName}}
  template:
    metadata:
      labels:
        app: {{$fullName}}
    spec:
      containers:
        - name: {{$fullName}}
          image: moreillon/food-manager:f062718f
          env:
            - name: MONGODB_URL
              value: {{ $mongodbUrl }}
            {{- if .Values.auth.enabled }}
            - name: IDENTIFICATION_URL
              value: {{ printf "%s/users/self" (include "food-manager.auth.url" .) }}
            {{- end }}
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/src/app/uploads
              name: {{$fullName}}
      volumes:
        - name: {{$fullName}}
          persistentVolumeClaim:
            claimName: {{$fullName}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$fullName}}
spec:
  type: NodePort
  selector:
    app: {{$fullName}}
  ports:
    - port: 80
      nodePort: 30022
