{{ $resourceName := "gui" }}
{{ $fullName := printf "%s-%s" (include "food-manager.fullName" .) $resourceName | trunc 63 | trimSuffix "-" }}
{{ $apiFullName := printf "%s-api" (include "food-manager.fullName" .) | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      containers:
      - name: {{ $fullName }}
        image: moreillon/food-manager-front
        ports:
        - containerPort: 80
        env:
        - name: VUE_APP_FOOD_MANAGER_API_URL
          value: /proxy/api
        - name: PROXY_API
          value: http://{{ $apiFullName  }}
        # TODO: Auth optional
        # - name: VUE_APP_LOGIN_URL
        #   value: /proxy/food-manager/auth/login
        # - name: VUE_APP_IDENTIFICATION_URL
        #   value: /proxy/food-manager/users/self


        
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
spec:
  selector:
    app: {{ $fullName }}
{{- if .Values.nodePort }}
  type: NodePort
  ports:
  - port: 80
    nodePort: {{ .Values.nodePort }}
{{- else }}
  type: ClusterIP
  ports:
  - port: 80
{{- end }}

