{{ $apiFullName := include "user-manager.prefix" . | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Secret
metadata:
  name: group-manager-env
type: Opaque
stringData:
  NEO4J_URL: {{ include "user-manager.neo4j.url" . }}
  NEO4J_USERNAME: {{ default "neo4j" .Values.neo4j.neo4j.username }}
  NEO4J_PASSWORD: {{ .Values.neo4j.neo4j.password }}
  IDENTIFICATION_URL: http://{{ $apiFullName  }}/users/self
