{{ $apiFullName := include "user-manager.prefix" . | trunc 63 | trimSuffix "-" }}
{{ $guiFullName := printf "%s-gui" (include "user-manager.prefix" .) | trunc 63 | trimSuffix "-" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kong.dblessConfig.configMap }}
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true
    services:
    - name: gui
      url: http://{{ $guiFullName }}
      routes:
      - name: gui
        paths:
        - /
    - name: api
      url: http://{{ $apiFullName  }}
      routes:
      - name: api
        paths:
        - /api
    - name: groups-gui
      url: http://{{ .Release.Name }}-groups-gui
      routes:
      - name: groups-gui
        paths:
        - /groups
    - name: groups-api
      url: http://{{ .Release.Name }}-groups-api
      routes:
      - name: groups-api
        paths:
        - /groups/api

