apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mosquitto
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - mqtt.{{ .Values.domain }}
    secretName: mosquitto-certs
  rules:
  - host: mqtt.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: mosquitto-wss
          servicePort: 9001
