apiVersion: v2
name: user-manager-mongodb
description: A Helm chart to deploy the User management and authentication microservice (MongoDB version)
type: application
version: 0.3.6
appVersion: 1.16.0

icon: https://cdn.maximemoreillon.com/logo/thick/logo.png

dependencies:
  - name: mongodb
    version: 13.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
