auth:
  jwt_secret: keyboardcat
  admin:
    username: admin
    password: admin

service:
  type: NodePort
  nodePort: 30080

ingress:
  enabled: false
  host: auth.example.com
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

# Bitnami MongoDB subchart
mongodb:
  enabled: true
  persistence:
    size: 100Gi
  auth:
    enabled: false
    # Dummy password to facilitate upgrades
    rootPassword: banana
