api:
  image: moreillon/user-manager-mongoose:v5.0.1
  jwt_secret: keyboardcat
  admin:
    username: admin
    password: admin

gui:
  image: moreillon/user-manager-front:v5.0.3


# Bitnami MongoDB subchart
mongodb:
  enabled: true
  persistence:
    size: 100Gi
  auth:
    enabled: false

# API Gateway
kong:
  enabled: true
  admin:
    enabled: false
  env:
    database: "off"
    dns_order: A,CNAME,LAST,SRV
  dblessConfig:
    configMap: kong-config
  ingressController:
    enabled: false
  proxy:
    type: NodePort
    http:
      nodePort: 31081
