apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{include "neo4j.fullname" .}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.persistence.size}}
