{{ $fullName := include "neo4j.fullName" .}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
spec:
  ports:
  - port: 7474
    name: http
  - port: 7687
    name: bolt
  selector:
    app: {{ $fullName }}
  # TODO: consider NodePort
  type: ClusterIP
