apiVersion: v1
kind: Service
metadata:
  name: {{include "neo4j.fullname" .}}
spec:
  ports:
    - port: 7474
      name: http
    - port: 7687
      name: bolt
  selector:
    app: {{include "neo4j.fullname" .}}
  # TODO: consider NodePort
  type: ClusterIP
