apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager
  template:
    metadata:
      labels:
        app: user-manager
    spec:
      containers:
      - name: user-manager
        image: moreillon/user-manager
        # Pull new image on restart
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # Get environment variables from secret
        env:
        - name: JWT_SECRET
          value: {{ .Values.token_secret }}
        - name: NEO4J_URL
          value: bolt://neo4j:7687
        - name: NEO4J_USERNAME
          value: {{ .Values.neo4j.username }}
        - name: NEO4J_PASSWORD
          value: {{ .Values.neo4j.password }}
