apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
stringData:

  JWT_SECRET: {{ .Values.jwt_secret }}
  ADMIN_USERNAME: {{ .Values.admin.username }}
  ADMIN_PASSWORD: {{ .Values.admin.password }}
