apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
stringData:

  JWT_SECRET: {{ .Values.jwt_secret }}
  NEO4J_USERNAME: {{ .Values.neo4j.username }}
  NEO4J_PASSWORD: {{ .Values.neo4j.password }}
  ADMIN_USERNAME: {{ .Values.admin.username }}
  ADMIN_PASSWORD: {{ .Values.admin.password }}
