apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:2.6
          ports:
            - containerPort: 8086
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: influxdb
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: {{.Values.credentials.username}}
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: {{.Values.credentials.password}}
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              value: {{.Values.influxdb.token}}
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: {{.Values.influxdb.org}}
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: {{.Values.influxdb.bucket}}
      volumes:
        - name: influxdb
          persistentVolumeClaim:
            claimName: influxdb
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  ports:
    - port: 8086
      # TODO: user customizable
      nodePort: 30086
  selector:
    app: influxdb
  type: NodePort
