apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-logger
  template:
    metadata:
      labels:
        app: mqtt-logger
    spec:
      containers:
        - name: mqtt-logger
          image: moreillon/mqtt-logger:9ffbf718
          env:
            # InfluxDB
            - name: INFLUXDB_URL
              # NOTE: port is necessary
              value: http://influxdb:8086
            - name: INFLUXDB_ORG
              value: {{.Values.influxdb.org}}
            - name: INFLUXDB_BUCKET
              value: {{.Values.influxdb.bucket}}
            - name: INFLUXDB_TOKEN
              value: {{.Values.influxdb.token}}
            # MongoDB
            - name: MONGODB_URL
              value: mongodb://mongo
            # MQTT
            # TODO: allow to use broker deployed with this chart
            - name: MQTT_URL
              value: {{.Values.mqtt.broker}}
            - name: MQTT_USERNAME
              value: {{.Values.mqtt.username}}
            - name: MQTT_PASSWORD
              value: {{.Values.mqtt.password}}
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-logger
spec:
  type: NodePort
  selector:
    app: mqtt-logger
  ports:
    - port: 80
      # TODO: default
      nodePort: {{.Values.backEnd.nodePort}}
