apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-logger-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-logger-front
  template:
    metadata:
      labels:
        app: mqtt-logger-front
    spec:
      containers:
        - name: mqtt-logger-front
          image: moreillon/mqtt-logger-front:50030b8b
          env:
            - name: VUE_APP_MQTT_LOGGER_API_URL
              value: /proxy/api
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-logger-front
spec:
  type: ClusterIP
  selector:
    app: mqtt-logger-front
  ports:
    - port: 80
