apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
        - name: {{.Values.name}}
          image: moreillon/mqtt-logger:9ffbf718
          env:
            # InfluxDB
            - name: INFLUXDB_URL
              # NOTE: port is necessary
              # TODO: allow user to use their own influxDB
              value: http://{{.Values.name}}-influxdb:8086
            - name: INFLUXDB_ORG
              value: {{.Values.influxdb.org}}
            - name: INFLUXDB_BUCKET
              value: {{.Values.influxdb.bucket}}
            - name: INFLUXDB_TOKEN
              value: {{.Values.influxdb.token}}
            # MongoDB
            - name: MONGODB_URL
              value: mongodb://{{.Values.name}}-mongo
            # MQTT
            # TODO: allow to use broker deployed with this chart
            - name: MQTT_URL
              value: {{.Values.backEnd.mqtt.broker}}
            - name: MQTT_USERNAME
              value: {{.Values.backEnd.mqtt.username}}
            - name: MQTT_PASSWORD
              value: {{.Values.backEnd.mqtt.password}}
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
  type: NodePort
  selector:
    app: {{.Values.name}}
  ports:
    - port: 80
      # TODO: default
      nodePort: {{.Values.backEnd.nodePort}}
