{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "face-recognition-fastapi.serviceAccountName" . }}
  labels:
{{ include "face-recognition-fastapi.labels" . | nindent 4 }}
{{- end -}}
