apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: user-manager-proxy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # connect to the certificate issuer
spec:
  tls:
  - hosts:
    - users.{{ .Values.domain }}
    secretName: user-manager-proxy
  rules:
  - host: users.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: user-manager-proxy
          servicePort: 80
