apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager-proxy
  template:
    metadata:
      labels:
        app: user-manager-proxy
    spec:
      containers:
      - name: user-manager-proxy:a3e8b41e
        image: moreillon/api-proxy
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: PROXY_API
          value: http://user-manager
        - name: PROXY_ROOT
          value: http://user-manager-front
