{{- if .Values.neo4j.enabled -}}
{{ $fullName := include "neo4j.fullName" .}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      volumes:
      - name: {{ $fullName }}
        persistentVolumeClaim:
          claimName: {{ $fullName }}
      containers:
      - name: {{ $fullName }}
        image: neo4j:4.4.16
        envFrom:
        - secretRef:
            name: {{include "user-manager.prefix" .}}-credentials
        ports:
        - containerPort: 7474 # Browser
        - containerPort: 7687 # Bolt
        volumeMounts:
        - mountPath: /data
          name: {{ $fullName }}
{{- end -}}