{{- if .Values.neo4j.enabled -}}
{{ $fullName := include "neo4j.fullName" .}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "100Gi" .Values.neo4j.pvcSize }}
{{- end -}}