{{- if .Values.neo4j.enabled -}}
{{ $fullName := include "neo4j.fullName" .}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
type: Opaque
stringData:
  NEO4J_AUTH: {{ .Values.neo4j.username }}/{{ .Values.neo4j.password }}
{{- end -}}