apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.name}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # TODO: customizable
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
        - name: {{.Values.name}}
          image: moreillon/food-manager
          env:
            # MongoDB
            - name: MONGODB_URL
              value: mongodb://{{ .Values.name }}-db
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/src/app/uploads
              name: {{.Values.name}}
      volumes:
        - name: {{.Values.name}}
          persistentVolumeClaim:
            claimName: {{.Values.name}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.name}}
  ports:
    - port: 80
