apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{include "food-manager.prefix" .}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # TODO: customizable
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "food-manager.prefix" .}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{include "food-manager.prefix" .}}
  template:
    metadata:
      labels:
        app: {{include "food-manager.prefix" .}}
    spec:
      containers:
        - name: {{include "food-manager.prefix" .}}
          image: moreillon/food-manager
          env:
            # DB
            - name: MONGODB_URL
              value: {{include "mongodb.url" .}}
            # Auth
            - name: IDENTIFICATION_URL
              value: http://{{ include "food-manager.prefix" . }}-{{ toYaml (index .Values "user-manager-mongoose" "prefix" ) }}-api/users/self
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/src/app/uploads
              name: {{include "food-manager.prefix" .}}
      volumes:
        - name: {{include "food-manager.prefix" .}}
          persistentVolumeClaim:
            claimName: {{include "food-manager.prefix" .}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{include "food-manager.prefix" .}}
spec:
  type: NodePort
  selector:
    app: {{include "food-manager.prefix" .}}
  ports:
    - port: 80
      nodePort: 30022
