{{- if .Values.mosquitto.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mosquitto.fullName" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.mosquitto.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mosquitto.fullName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mosquitto.fullName" . }}
  template:
    metadata:
      labels:
        app: {{ include "mosquitto.fullName" . }}
    spec:
      containers:
        - name: {{ include "mosquitto.fullName" . }}
          image: eclipse-mosquitto
          ports:
            - containerPort: 1883 # MQTT
            - containerPort: 9001 # WSS
          volumeMounts:
            - mountPath: /mosquitto/config/
              name: config
            - mountPath: /mosquitto/data/
              name: data
      volumes:
        - name: config
          configMap:
            name: {{ include "mosquitto.fullName" . }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mosquitto.fullName" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullName" . }}
data:
  mosquitto.conf: |

    persistence true
    persistence_location /mosquitto/data/

    log_dest stdout

    # Change this to enforce authentication
    # TODO: have option to add authentication
    allow_anonymous true

    # Default listener for direct MQTT traffic
    listener 1883
    protocol mqtt

    # Listener for MQTT traffic over Websockets
    listener 9001
    protocol websockets

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullName" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "mosquitto.fullName" . }}
  ports:
    - name: mqtt
      port: 1883
      nodePort: {{.Values.mosquitto.services.nodePorts.mqtt }}
    - name: ws
      port: 9001
      nodePort: {{.Values.mosquitto.services.nodePorts.ws }}
{{- end }}
