apiVersion: v2
name: camera-viewer
description: A Helm chart to deploy the camera-viewer aplication

type: application

version: 0.2.0

appVersion: "1.16.0"

icon: https://raw.githubusercontent.com/maximemoreillon/helm-repository/master/charts/camera-viewer/icon.png

dependencies:
  - name: user-manager-mongodb
    version: 0.3.5
    repository: https://maximemoreillon.github.io/helm-repository
    condition: auth.enabled
    alias: auth

  - name: mongodb
    version: 13.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled

  - name: kong
    version: 2.39.2
    repository: https://charts.konghq.com
    condition: kong.enabled
