{{ $resourceName := "proxy" }}
{{ $fullname := printf "%s-%s" (include "user-manager.fullname" .) $resourceName | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullname }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ $fullname }}
        image: moreillon/api-proxy:27b57877
        ports:
        - containerPort: 80
        env:
        - name: PATH_PREFIX
          value: ""
        # TODO: Might not match if truncated
        - name: PROXY_API
          value: http://{{ include "user-manager.fullname" . }}-api
        - name: PROXY_ROOT
          value: http://{{ include "user-manager.fullname" . }}-gui
