{{ $ingressEnabled := eq (include "user-manager.ingress.enabled" .) "true"}}
{{- if $ingressEnabled -}}
{{ $resourceName := "proxy" }}
{{ $fullname := printf "%s-%s" (include "user-manager.fullname" .) $resourceName | trunc 63 | trimSuffix "-" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  annotations: {{ include "user-manager.ingress.annotations" .}}
spec:
  tls:
    - hosts:
        - {{ include "user-manager.ingress.host" . }}
      secretName: {{ $fullname }}
  rules:
    - host: {{ include "user-manager.ingress.host" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: {{ $fullname }}
                port:
                  number: 80
{{- end }}
