{{ $resourceName := "proxy" }}
{{ $fullname := printf "%s-%s" (include "user-manager.fullname" .) $resourceName | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
spec:
  selector:
    app: {{ $fullname }}
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
  - port: 80
    {{ if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}


