apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "100Gi" .Values.neo4j.pvcSize }}
