apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "resources.prefix" . }}-neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "100Gi" .Values.neo4j.pvcSize }}
