apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-neo4j
spec:
  ports:
  - port: 7474
    name: http
  - port: 7687
    name: bolt
  selector:
    app: {{ .Release.Name }}-neo4j
  # TODO: consider NodePort
  type: ClusterIP
