{{ $fullName := include "user-manager.prefix" . | trunc 63 | trimSuffix "-" }}
# Warning: hardcoded

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      containers:
      - name: {{ $fullName }}
        image: moreillon/user-manager:v4.5.3
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
           name: {{ $fullName }}
        env:
        - name: NEO4J_URL
          value: {{ include "user-manager.neo4j.url" . }}
