{{ $fullName := include "user-manager.prefix" . | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
type: Opaque
stringData:

  JWT_SECRET: {{.Values.auth.jwt_secret}}

  ADMIN_USERNAME: {{.Values.auth.admin.username}}
  ADMIN_PASSWORD: {{.Values.auth.admin.password}}

  NEO4J_USERNAME: {{ default "neo4j" .Values.neo4j.neo4j.username}}
  NEO4J_PASSWORD: {{.Values.neo4j.neo4j.password}}
