{{ $fullName := include "user-manager.prefix" . | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
type: Opaque
stringData:
  # User manager API
  JWT_SECRET: {{.Values.jwt_secret}}
  ADMIN_USERNAME: {{.Values.admin.username}}
  ADMIN_PASSWORD: {{.Values.admin.password}}
  NEO4J_USERNAME: {{.Values.neo4j.username}}
  NEO4J_PASSWORD: {{.Values.neo4j.password}}
