{{ $fullName := include "user-manager.prefix" . | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
spec:
  type: NodePort
  selector:
    app: {{ $fullName }}
  ports:
  - port: 80
    nodePort: {{ .Values.nodePorts.api }}
