# Default values for food-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global needed for subcharts
global:
  ingress:
    host: food.test.home.maximemoreillon.com

  # Using integrated MongoDB by setting url to null
  mongodb:
    url: mongodb://192.168.1.2:30717

nodePort: 30400

# TODO: consider global
ingress:
  enabled: false

user-manager-mongoose:
  prefix: users
  ingress:
    enabled: false
    subdomain: users
  mongodb:
    enabled: false
