{{ $resourceName := "api" }}
{{ $fullname := printf "%s-%s" (include "user-manager.fullname" .) $resourceName | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.api.jwt_secret }}
  ADMIN_USERNAME: {{ .Values.api.admin.username }}
  ADMIN_PASSWORD: {{ .Values.api.admin.password }}
