apiVersion: v2
name: mqtt-logger
description: A Helm chart for to deploy MQTT Logger

type: application

version: 0.2.2

appVersion: "1.16.0"

icon: https://raw.githubusercontent.com/maximemoreillon/helm-repository/master/charts/mqtt-logger/icon.png

dependencies:
  - name: mongodb
    version: 13.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled

  # NOTE: The official Influxdata helm chart seems to be for v1.8.x
  - name: influxdb
    version: 5.4.16
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled
