apiVersion: v2
name: mqtt-logger
description: A Helm chart to deploy MQTT Logger

type: application

version: 0.3.0

appVersion: "1.16.0"

icon: https://raw.githubusercontent.com/maximemoreillon/helm-repository/master/charts/mqtt-logger/icon.png

dependencies:
  - name: mongodb
    version: 13.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled

  # NOTE: The official Influxdata helm chart seems to be for v1.8.x
  - name: influxdb
    version: 5.4.16
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled

  - name: kong
    version: 2.39.2
    repository: https://charts.konghq.com
    condition: kong.enabled
