mqtt:
  # url: mqtt://192.168.1.2:1883
  username: externalmqttusername
  password: externalmqtt

# InfluxDB helm chart from the Bitnami repo
influxdb:
  enabled: true
  auth:
    admin:
      username: admin
      password: keyboardcat
      token: 5Qlnkzp3kW6RDVMHlktMzDCQEG5CBGHf59J-5x5lK2g9BVCtoYdgrI9aqnYi5fNIB0EfJoUDQ0bWHkGqkr5qRA==
      org: mqtt_logger
      bucket: mqtt_logger
  persistence:
    size: 50Gi

  # nodePort: 30402
  # pvc: 100Gi

# MongoDB subchart from Bitnami repo
mongodb:
  enabled: true
  persistence:
    size: 10Gi
  auth:
    enabled: false

# Integrated MQTT broker
mosquitto:
  enabled: false
  persistence:
    size: 10Gi
  service:
    nodePorts:
      mqtt: 30403
      ws: 30404

# API Gateway
kong:
  enabled: true
  admin:
    enabled: false # Do not create a service for the admin API
  manager:
    enabled: false # Do not create a service for Kong Manager
  ingressController:
    enabled: false
  env:
    database: "off"
    dns_order: A,CNAME,LAST,SRV
  dblessConfig:
    configMap: kong-config
  proxy:
    type: NodePort
    http:
      nodePort: 31081
    tls:
      enabled: false
