mqtt:
  # url: mqtt://192.168.1.2:1883
  username: externalmqttusername
  password: externalmqtt

service:
  nodePorts:

backEnd:
  nodePort: 30400
  # TODO: allow user to configure their own InfluxDB and MongoDB

frontEnd:
  nodePort: 30401

# InfluxDB helm chart from the Bitnami repo
influxdb:
  enabled: true
  auth:
    admin:
      username: admin
      password: keyboardcat
      token: 5Qlnkzp3kW6RDVMHlktMzDCQEG5CBGHf59J-5x5lK2g9BVCtoYdgrI9aqnYi5fNIB0EfJoUDQ0bWHkGqkr5qRA==
      org: mqtt_logger
      bucket: mqtt_logger
  persistence:
    size: 50Gi

  # nodePort: 30402
  # pvc: 100Gi

# MongoDB subchart from Bitnami repo
mongodb:
  enabled: true
  persistence:
    size: 10Gi
  auth:
    enabled: false

# Integrated MQTT broker
mosquitto:
  enabled: false
  persistence:
    size: 10Gi
  service:
    nodePorts:
      mqtt: 30403
      ws: 30404
