# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "group-manager.prefix" . }}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "group-manager.prefix" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "group-manager.prefix" . }}-api
    spec:
      containers:
      - name: {{ include "group-manager.prefix" . }}-api
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: {{ include "group-manager.prefix" . }}-env
        env:
        {{- range .Values.gui.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "group-manager.prefix" . }}-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "group-manager.prefix" . }}-api
  ports:
  - port: 80
    nodePort: {{ .Values.service.nodePort }}

