apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "group-manager.prefix" . }}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "group-manager.prefix" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "group-manager.prefix" . }}-api
    spec:
      containers:
      - name: {{ include "group-manager.prefix" . }}-api
        image: moreillon/group-manager:v4.9.0
        ports:
        - containerPort: 80
        env:
        - name: NEO4J_URL
          value: {{ include "group-manager.neo4j.url" . }}
        - name: NEO4J_USERNAME
          value: {{ .Values.neo4j.username }}
        - name: NEO4J_PASSWORD
          value: {{ .Values.neo4j.password }}
        - name: IDENTIFICATION_URL
          value: {{ include "group-manager.auth.url" . }}/users/self
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "group-manager.prefix" . }}-api
spec:
  type: NodePort
  selector:
    app: {{ include "group-manager.prefix" . }}-api
  ports:
  - port: 80
    nodePort: {{ .Values.nodePorts.api }}

