apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "group-manager.prefix" . }}-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "group-manager.prefix" . }}-gui
  template:
    metadata:
      labels:
        app: {{ include "group-manager.prefix" . }}-gui
    spec:
      containers:
      - name: {{ include "group-manager.prefix" . }}-gui
        image: {{ .Values.gui.image}}
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: {{ include "group-manager.prefix" . }}-env
        env:       
        {{- range .Values.gui.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "group-manager.prefix" . }}-gui
spec:
  type: ClusterIP
  selector:
    app: {{ include "group-manager.prefix" . }}-gui
  ports:
  - port: 80

