apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "group-manager.prefix" . }}-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "group-manager.prefix" . }}-proxy
  template:
    metadata:
      labels:
        app: {{ include "group-manager.prefix" . }}-proxy
    spec:
      containers:
      - name: {{ include "group-manager.prefix" . }}-proxy
        # TODO: tag
        image: moreillon/api-proxy
        ports:
        - containerPort: 80
        env:
        - name: PROXY_ROOT
          value: http://{{ include "group-manager.prefix" . }}-gui
        - name: PROXY_API
          value: http://{{ include "group-manager.prefix" . }}-api
        - name: PROXY_AUTH
          value: {{ include "group-manager.auth.url" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "group-manager.prefix" . }}-proxy
spec:
  type: NodePort
  selector:
    app: {{ include "group-manager.prefix" . }}-proxy
  ports:
  - port: 80
    nodePort: {{ .Values.nodePorts.gui }}
---
{{- if eq (include "group-manager.ingress.enabled" .) "true"}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "group-manager.prefix" . }}-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{ include "group-manager.ingress.host" . }}
      secretName: {{ include "group-manager.prefix" . }}-proxy
  rules:
    - host: {{ include "group-manager.ingress.host" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: {{ include "group-manager.prefix" . }}-proxy
                port:
                  number: 80
{{- end }}
